---
- name: Run prerequisites
  ansible.builtin.import_tasks: prerequisites.yml

- name: Configure prometheus
  ansible.builtin.import_tasks: prometheus.yml

- name: Configure grafana
  ansible.builtin.import_tasks: grafana.yml

- name: Configure loki
  ansible.builtin.import_tasks: loki.yml

- name: Configure alertmanager
  ansible.builtin.import_tasks: alertmanager.yml
