---
app_container_name: "web-app"
app_container_image: "nginx:alpine"
app_container_port: "80"
app_server_private_ip: ""
monitoring_server_private_ip: ""

app_secret_key: "{{ vault_app_secret_key }}"
