---
- name: Install auditd packages
  ansible.builtin.apt:
    name:
      - auditd
      - audispd-plugins
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install audit hardening rules
  ansible.builtin.template:
    src: hardening.rules.j2
    dest: "{{ common_audit_rules_file }}"
    owner: root
    group: root
    mode: "0640"
  become: true
  notify: Reload audit rules

- name: Ensure auditd is enabled and running
  ansible.builtin.systemd_service:
    name: auditd
    state: started
    enabled: true
  become: true
