---
- name: Restart prometheus
  ansible.builtin.systemd_service:
    name: prometheus
    state: restarted

- name: Restart grafana
  ansible.builtin.systemd_service:
    name: grafana-server
    state: restarted

- name: Restart loki
  ansible.builtin.systemd_service:
    name: loki
    state: restarted

- name: Restart alertmanager
  ansible.builtin.systemd_service:
    name: alertmanager
    state: restarted
