---
- name: Configure docker
  ansible.builtin.import_tasks: docker.yml

- name: Configure nginx container
  ansible.builtin.import_tasks: nginx_container.yml

- name: Configure alloy
  ansible.builtin.import_tasks: alloy.yml
