---
- name: Configure Linux infrastructure
  hosts: all
  become: true
  remote_user: "{{ automation_user }}"

  roles:
    - common

- name: Configure application servers
  hosts: app
  become: true
  remote_user: "{{ automation_user }}"

  roles:
    - app

- name: Configure monitoring server
  hosts: monitoring
  become: true
  remote_user: "{{ automation_user }}"

  roles:
    - monitoring
