name: Terraform Plan

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: terraform-${{ github.repository }}
  cancel-in-progress: false

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      TF_STATE_BUCKET: ${{ vars.TF_STATE_BUCKET }}
      ALLOWED_SSH_CIDR: ${{ vars.ALLOWED_SSH_CIDR }}
      SSH_PUBLIC_KEY: ${{ vars.SSH_PUBLIC_KEY }}
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.2.4
        with:
          role-to-assume: ${{ vars.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: GitHubActionsTerraformPlan

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.16.0"

      - name: Validate Terraform variables
        run: |
          test -n "$AWS_REGION" || {
          echo "::error::AWS_REGION is not configured."
          exit 1
          }

          test -n "$TF_STATE_BUCKET" || {
          echo "::error::TF_STATE_BUCKET is not configured."
          exit 1
          }

          test -n "$ALLOWED_SSH_CIDR" || {
          echo "::error::ALLOWED_SSH_CIDR is not configured."
          exit 1
          }

          test -n "$SSH_PUBLIC_KEY" || {
          echo "::error::SSH_PUBLIC_KEY is not configured."
          exit 1
          }

      - name: Terraform init
        working-directory: terraform
        run: |
          terraform init \
           -backend-config="bucket=${TF_STATE_BUCKET}" \
           -backend-config="region=${AWS_REGION}"

      - name: Terraform plan
        working-directory: terraform
        env:
          TF_VAR_aws_region: ${{ vars.AWS_REGION }}
          TF_VAR_allowed_ssh_cidr: ${{ vars.ALLOWED_SSH_CIDR }}
          TF_VAR_ssh_public_key: ${{ vars.SSH_PUBLIC_KEY }}
        run: |
          terraform plan \
          -input=false \
          -no-color
